# Generated by Django 4.2.30 on 2026-07-11 13:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. HDFC Bank shares, Axis Bluechip Fund', max_length=100)),
                ('investment_type', models.CharField(choices=[('stocks', 'Stocks'), ('mutual_funds', 'Mutual Funds'), ('fixed_deposit', 'Fixed Deposit'), ('real_estate', 'Real Estate'), ('gold', 'Gold'), ('crypto', 'Cryptocurrency'), ('ppf', 'PPF / EPF'), ('other', 'Other')], max_length=20)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Update this whenever you check your latest statement', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(help_text='Date of investment')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
